#Log Level Configuration for hikari CP
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
        
#Actuator Management Endpoints Configuration        
management:
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'
        
spring:
  datasource:
    book:
      #driver-class-name: org.hsqldb.jdbc.JDBCDriver
      driver-class-name: oracle.jdbc.driver.OracleDriver
      #jdbc-url: jdbc:hsqldb:hsql://localhost/xdb
      jdbc-url: jdbc:oracle:thin:@35.188.144.55:1521/pdb1
      
      username: sri
      password: pass
    product:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:tcp://localhost/~/test;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password: ""
     