#Log Level Configuration for hikari CP
logging:
  level:
    com:
      zaxxer:
        hikari: DEBUG
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

#Actuator Management Endpoints Configuration
# configuration
management:
  endpoint:
    env:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: '*'

server:
  port: 9081
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: testing
    keyStoreType: PKCS12
    keyAlias: tomcat
 
security:
  require-ssl: true

